<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Eswar-PC" name="Default test" tests="1" failures="1" timestamp="9 May 2015 18:31:08 GMT" time="75.693" errors="0">
  <testcase name="test_TC01_Login" time="75.248" classname="com.gmail.tests.TC01_Login">
    <failure type="java.lang.AssertionError" message="Element  &amp;apos;//a[contains(@title,&amp;apos;Account&amp;apos;)]&amp;apos; =not found after 10 seconds ">
      <![CDATA[java.lang.AssertionError: Element  '//a[contains(@title,'Account')]' =not found after 10 seconds 
	at org.testng.Assert.fail(Assert.java:94)
	at com.selenium.webdriver.DriverLib.fWaitForElementPresent(DriverLib.java:419)
	at com.selenium.webdriver.DriverLib.fClickElement(DriverLib.java:1116)
	at com.gmail.pageobjects.LoginPage.fLogout(LoginPage.java:50)
	at com.gmail.tests.TC01_Login.test_TC01_Login(TC01_Login.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- test_TC01_Login -->
</testsuite> <!-- Default test -->
